version: 5.0.4-{build}
clone_folder: c:\projects\ntrprs
image: Visual Studio 2017

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\run-tests.ps1
  
deploy:
  provider: NuGet
  api_key:
    secure: QQQ2lpOVxxjRGCF7xGtWri1yov8rDUENp7lX8y0cymZPEyV8grMMveniEti3Fr/9
  skip_symbols: false
  artifact: /.*\.nupkg/
  
artifacts:
  - path: 'artifacts\*.nupkg'